'use strict';
//This route file was generated by ChatGPT and then manually edited.
// Ensure helpers is required and controllers is received as an argument
const helpers = require('./helpers');

module.exports.init = function (router, middleware, controllers) {
	// Server-rendered page for full loads
	router.get('/filter', middleware.buildHeader, async (req, res) => {
		return res.render('filter', {});
	});

	// API route -> controller
	router.get('/api/filter/posts', helpers.tryRoute(controllers.filter.posts));
};
