'use strict';
//This controller file was generated by ChatGPT and then manually edited. 
const Posts = require('../posts');

module.exports.posts = async function (req, res) {
	try {
		const startRaw = req.query.start;
		const endRaw = req.query.end;
		if (!startRaw || !endRaw) {
			return res.status(400).json({ success: false, error: 'missing_start_or_end' });
		}

		const startMs = Date.parse(startRaw);
		const endMs = Date.parse(endRaw);
		if (isNaN(startMs) || isNaN(endMs)) {
			return res.status(400).json({ success: false, error: 'invalid_date' });
		}
		
		const offset = Number.isFinite(Number(req.query.offset)) ? parseInt(req.query.offset, 10) : 0;
		const limit = Number.isFinite(Number(req.query.limit)) ? Math.min(parseInt(req.query.limit, 10), 200) : 50;
		const stop = offset + limit - 1;
		const cid = (typeof req.query.cid !== 'undefined') ? parseInt(req.query.cid, 10) : -1;
		const uid = (req.uid || (req.user && req.user.uid) || 0);
		const posts = await Posts.getPostsByTimeRange(uid, startMs, endMs, offset, stop, cid);
		return res.json({ success: true, posts: posts || [] });
	} catch (err) {
		return res.status(500).json({ success: false, error: err.message });
	}
};